# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/workflows/*.yml'
      - '!**/workflows/maven.yml'
  pull_request:
    paths-ignore:
      - '**/workflows/*.yml'
      - '!**/workflows/maven.yml'

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 7
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        java: [ 8, 11, 17, 21, 24 ]
        os: [ubuntu-latest]
        experimental: [false]
        # Don't need to run all javas on all OSes
        include:
          - java: 8
            os: macos-13
            experimental: false
          - java: 8
            os: windows-latest
            experimental: false
          # Update java 8/ubuntu to add deploy step
          - java: 8
            os: ubuntu-latest
            experimental: false
            deploy: true
          # Experimental build
          - java: 25-ea
            experimental: true        
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        # these values cause the plugin to set up the Maven settings.xml file
        server-id: apache.snapshots.https # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: NEXUS_USER # env variable for username in deploy
        server-password: NEXUS_PW # env variable for token in deploy
    - name: Build and test with Maven
      run: mvn --errors --show-version --batch-mode --no-transfer-progress -Ddoclint=all
# Add  -Pslf4j-simple to enable logging above
    - name: Deploy SNAPSHOT using minimal build
      if: matrix.deploy && github.repository == 'apache/commons-net' && github.ref_name == 'master'
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PW: ${{ secrets.NEXUS_PW }}
      run: >
        echo "Deploy SNAPSHOT" >> $GITHUB_STEP_SUMMARY;
        mvn --show-version --batch-mode --no-transfer-progress deploy -Dgpg.skip 
        -DskipTests -Drat.skip -Djacoco.skip -Dcyclonedx.skip -Dspotbugs.skip -Dspdx.skip -Dpmd.skip
